spring.application.name=DevTradeBackend

spring.datasource.url=jdbc:mariadb://187.77.138.171:3306/devtrade
spring.datasource.username=root
spring.datasource.password=pasith1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Enable SQL logging for debugging
spring.jpa.show-sql=true

# Server port
server.port=8080
